#!/usr/bin/env python3
"""
Fetch active free-game offers and write them to free_games.js.

The script is intentionally defensive:
- if every store fails, the previous file is kept untouched
- if only some stores fail, previous entries for those stores are preserved
- expired offers are always removed before writing the merged output
"""

from __future__ import annotations

import datetime as dt
import json
import pathlib
import re
from collections import defaultdict
from typing import Any
from urllib.parse import urljoin

try:
    import requests
    from bs4 import BeautifulSoup
except ImportError:  # pragma: no cover - handled at runtime in CI/local use
    requests = None
    BeautifulSoup = None


ROOT = pathlib.Path(__file__).resolve().parent
OUTPUT = ROOT / "free_games.js"
USER_AGENT = "Coophubs Free Games Bot/1.0 (+https://coophubs.net)"
TIMEOUT = 20
NOW = dt.datetime.now(dt.timezone.utc)


class FetchError(RuntimeError):
    """Raised when a store cannot be fetched or parsed confidently."""


def parse_iso_datetime(value: str | None) -> dt.datetime | None:
    if not value:
        return None
    text = value.strip()
    if not text:
        return None
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        parsed = dt.datetime.fromisoformat(text)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=dt.timezone.utc)
    return parsed.astimezone(dt.timezone.utc)


def to_iso_z(value: dt.datetime) -> str:
    return value.astimezone(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def normalize_offer(raw: dict[str, Any]) -> dict[str, str] | None:
    title = (raw.get("title") or "").strip()
    store = (raw.get("store") or "").strip().lower()
    store_url = (raw.get("storeUrl") or "").strip()
    image_url = (raw.get("imageUrl") or "").strip()
    expires = parse_iso_datetime(raw.get("freeUntil"))

    if not title or not store or not store_url or not expires or expires <= NOW:
        return None

    return {
        "title": title,
        "store": store,
        "imageUrl": image_url,
        "storeUrl": store_url,
        "freeUntil": to_iso_z(expires),
    }


def dedupe_offers(offers: list[dict[str, str]]) -> list[dict[str, str]]:
    seen = set()
    deduped = []
    for offer in sorted(offers, key=lambda item: (item["freeUntil"], item["store"], item["title"].lower())):
        key = (offer["store"], offer["title"].strip().lower())
        if key in seen:
            continue
        seen.add(key)
        deduped.append(offer)
    return deduped


def load_previous_offers() -> list[dict[str, str]]:
    if not OUTPUT.is_file():
        return []

    text = OUTPUT.read_text(encoding="utf-8")
    match = re.search(r"const\s+freeGames\s*=\s*(\[[\s\S]*\])\s*;?\s*$", text)
    if not match:
        raise FetchError("Existing free_games.js has an unexpected format")

    try:
        payload = json.loads(match.group(1))
    except json.JSONDecodeError as exc:
        raise FetchError(f"Existing free_games.js is not valid JSON payload: {exc}") from exc

    if not isinstance(payload, list):
        raise FetchError("Existing free_games.js does not contain an array payload")

    offers = []
    for item in payload:
        if isinstance(item, dict):
            offer = normalize_offer(item)
            if offer:
                offers.append(offer)
    return dedupe_offers(offers)


def write_offers(offers: list[dict[str, str]]) -> None:
    payload = json.dumps(dedupe_offers(offers), ensure_ascii=False, indent=2)
    OUTPUT.write_text(f"// Auto-generated by fetch_free_games.py\nconst freeGames = {payload};\n", encoding="utf-8")


def get_session():
    if requests is None or BeautifulSoup is None:
        raise SystemExit("Missing dependencies: install requests and beautifulsoup4 before running fetch_free_games.py")

    session = requests.Session()
    session.headers.update(
        {
            "User-Agent": USER_AGENT,
            "Accept-Language": "en-US,en;q=0.9",
        }
    )
    return session


def parse_end_from_html(html_text: str) -> dt.datetime | None:
    patterns = [
        r'"endTime"\s*:\s*"([^"]+)"',
        r'"end_date"\s*:\s*"([^"]+)"',
        r'"endsAt"\s*:\s*"([^"]+)"',
        r'"validUntil"\s*:\s*"([^"]+)"',
    ]
    for pattern in patterns:
        match = re.search(pattern, html_text)
        if match:
            parsed = parse_iso_datetime(match.group(1))
            if parsed:
                return parsed
    return None


def choose_image(images: list[dict[str, Any]] | None) -> str:
    if not images:
        return ""
    preferred_types = (
        "DieselStoreFrontWide",
        "OfferImageWide",
        "VaultClosed",
        "Thumbnail",
    )
    for preferred in preferred_types:
        for image in images:
            if image.get("type") == preferred and image.get("url"):
                return image["url"]
    for image in images:
        url = image.get("url")
        if url:
            return url
    return ""


def extract_epic_slug(item: dict[str, Any]) -> str | None:
    mappings = item.get("catalogNs", {}).get("mappings") or []
    for mapping in mappings:
        page_slug = mapping.get("pageSlug")
        if page_slug:
            return page_slug

    offer_mappings = item.get("offerMappings") or []
    for mapping in offer_mappings:
        page_slug = mapping.get("pageSlug")
        if page_slug:
            return page_slug

    for key in ("productSlug", "urlSlug", "slug"):
        slug = item.get(key)
        if slug:
            return slug.strip("/")

    return None


def fetch_epic_offers(session) -> list[dict[str, str]]:
    url = "https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?locale=en-US&country=US&allowCountries=US"
    response = session.get(url, timeout=TIMEOUT)
    response.raise_for_status()
    payload = response.json()

    elements = (
        payload.get("data", {})
        .get("Catalog", {})
        .get("searchStore", {})
        .get("elements")
    ) or payload.get("elements") or []

    if not isinstance(elements, list):
        raise FetchError("Epic response schema changed")

    offers = []
    for item in elements:
        if not isinstance(item, dict):
            continue

        title = (item.get("title") or "").strip()
        if not title:
            continue

        price = item.get("price", {}).get("totalPrice", {})
        if price.get("discountPrice") != 0:
            continue

        promotions = item.get("promotions") or {}
        promo_groups = promotions.get("promotionalOffers") or []
        for group in promo_groups:
            for promo in group.get("promotionalOffers") or []:
                start_at = parse_iso_datetime(promo.get("startDate"))
                end_at = parse_iso_datetime(promo.get("endDate"))
                if not start_at or not end_at:
                    continue
                if start_at > NOW or end_at <= NOW:
                    continue

                slug = extract_epic_slug(item)
                if not slug:
                    continue

                offer = normalize_offer(
                    {
                        "title": title,
                        "store": "epic",
                        "imageUrl": choose_image(item.get("keyImages")),
                        "storeUrl": f"https://store.epicgames.com/en-US/p/{slug}",
                        "freeUntil": to_iso_z(end_at),
                    }
                )
                if offer:
                    offers.append(offer)

    return dedupe_offers(offers)


def fetch_steam_offers(session) -> list[dict[str, str]]:
    url = "https://store.steampowered.com/api/featuredcategories?cc=us&l=en"
    response = session.get(url, timeout=TIMEOUT)
    response.raise_for_status()
    payload = response.json()

    items = payload.get("specials", {}).get("items")
    if not isinstance(items, list):
        raise FetchError("Steam response schema changed")

    offers = []
    for item in items:
        if not isinstance(item, dict):
            continue

        if int(item.get("discount_percent") or 0) != 100:
            continue

        discount_expiration = item.get("discount_expiration")
        if not discount_expiration:
            continue

        end_at = dt.datetime.fromtimestamp(int(discount_expiration), tz=dt.timezone.utc)
        if end_at <= NOW:
            continue

        original_price = int(item.get("original_price") or 0)
        if original_price <= 0:
            continue

        app_id = item.get("id")
        if not app_id:
            continue

        offer = normalize_offer(
            {
                "title": item.get("name") or f"Steam App {app_id}",
                "store": "steam",
                "imageUrl": item.get("large_capsule_image")
                or item.get("header_image")
                or item.get("small_capsule_image")
                or "",
                "storeUrl": f"https://store.steampowered.com/app/{app_id}/",
                "freeUntil": to_iso_z(end_at),
            }
        )
        if offer:
            offers.append(offer)

    return dedupe_offers(offers)


def fetch_gog_offers(session) -> list[dict[str, str]]:
    url = "https://www.gog.com/en/"
    response = session.get(url, timeout=TIMEOUT)
    response.raise_for_status()
    html_text = response.text
    soup = BeautifulSoup(html_text, "html.parser")

    link = soup.select_one('a[href*="/giveaway/"]')
    if not link:
        if "giveaway" not in html_text.lower():
            return []
        raise FetchError("GOG giveaway markers found but no giveaway link could be parsed")

    end_at = parse_end_from_html(html_text)
    if not end_at:
        raise FetchError("GOG giveaway found but expiry could not be parsed")

    title = (
        (link.get("aria-label") or "").strip()
        or (link.get_text(" ", strip=True) or "").replace("Giveaway", "").strip()
    )
    image = ""
    img = link.find("img")
    if img:
        image = (img.get("src") or img.get("data-src") or "").strip()
        if not title:
            title = (img.get("alt") or "").strip()
    if not title:
        title = "GOG Giveaway"

    offer = normalize_offer(
        {
            "title": title,
            "store": "gog",
            "imageUrl": image,
            "storeUrl": urljoin(url, link.get("href", "")),
            "freeUntil": to_iso_z(end_at),
        }
    )
    return [offer] if offer else []


def fetch_humble_offers(session) -> list[dict[str, str]]:
    url = "https://www.humblebundle.com/store"
    response = session.get(url, timeout=TIMEOUT)
    response.raise_for_status()
    html_text = response.text
    soup = BeautifulSoup(html_text, "html.parser")

    link = soup.select_one('a[href*="/store/"][href*="free"]')
    if not link:
        if "free" not in html_text.lower():
            return []
        raise FetchError("Humble free-offer markers found but no offer link could be parsed")

    end_at = parse_end_from_html(html_text)
    if not end_at:
        raise FetchError("Humble offer found but expiry could not be parsed")

    title = (
        (link.get("aria-label") or "").strip()
        or (link.get_text(" ", strip=True) or "").strip()
    )
    image = ""
    img = link.find("img")
    if img:
        image = (img.get("src") or img.get("data-src") or "").strip()
        if not title:
            title = (img.get("alt") or "").strip()
    if not title:
        title = "Humble Free Game"

    offer = normalize_offer(
        {
            "title": title,
            "store": "humble",
            "imageUrl": image,
            "storeUrl": urljoin(url, link.get("href", "")),
            "freeUntil": to_iso_z(end_at),
        }
    )
    return [offer] if offer else []


def main() -> int:
    previous_offers = load_previous_offers()
    previous_by_store: dict[str, list[dict[str, str]]] = defaultdict(list)
    for offer in previous_offers:
        previous_by_store[offer["store"]].append(offer)

    session = get_session()
    fetchers = {
        "epic": fetch_epic_offers,
        "steam": fetch_steam_offers,
        "gog": fetch_gog_offers,
        "humble": fetch_humble_offers,
    }

    merged_by_store: dict[str, list[dict[str, str]]] = {}
    successful_stores = 0

    for store, fetcher in fetchers.items():
        try:
            offers = dedupe_offers(fetcher(session))
            merged_by_store[store] = offers
            successful_stores += 1
            print(f"[{store}] success: {len(offers)} active offers")
        except Exception as exc:
            fallback = dedupe_offers(previous_by_store.get(store, []))
            merged_by_store[store] = fallback
            print(f"[{store}] fallback: {len(fallback)} preserved offers ({exc})")

    if successful_stores == 0:
        print("No store updated successfully. Keeping free_games.js unchanged.")
        return 0

    merged = dedupe_offers([offer for offers in merged_by_store.values() for offer in offers])
    write_offers(merged)
    print(f"Wrote {len(merged)} total active offers to {OUTPUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
