// Auto-generated by fetch_free_games.py
const freeGames = [
  {
    "title": "Deponia",
    "store": "steam",
    "imageUrl": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/214340/header.jpg?t=1772651228",
    "storeUrl": "https://store.steampowered.com/app/214340/",
    "freeUntil": "2026-03-16T17:00:00Z"
  },
  {
    "title": "Cozy Grove",
    "store": "epic",
    "imageUrl": "https://cdn1.epicgames.com/768ec2d3b5114ac4a800631b12ee3f31/offer/CG-2560x1440-570add3e55ecf729bd4f3a221ca7927a.jpg",
    "storeUrl": "https://store.epicgames.com/en-US/p/cozy-grove",
    "freeUntil": "2026-03-19T15:00:00Z"
  },
  {
    "title": "Isonzo",
    "store": "epic",
    "imageUrl": "https://cdn1.epicgames.com/offer/30de69013f3b41b0ba594a8ef3b693ba/EGS_Isonzo_BlackMillGames_S1_2560x1440-c45b9d495ea324c69ad872aeccc9fb7d",
    "storeUrl": "https://store.epicgames.com/en-US/p/isonzo",
    "freeUntil": "2026-03-19T15:00:00Z"
  }
];
